### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by ud0y** [gzoumpourlis/DEAP_MNE_preprocessing#2]
Sir, I am trying to get the raw dataset of DEAP for a long time. But I could not get so. Can you please help me with the dataset?

**Comment by gzoumpourlis** [comment]
Hi, all the necessary instructions are mentioned in the dataset download [page](https://www.eecs.qmul.ac.uk/mmv/datasets/deap/download.html). Also make sure you've read carefully the EULA document.
